spring:
  redis:
    host: 47.99.108.112
    port: 6379
    password: dzyx6379cz
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 2
  datasource:
    url: jdbc:mysql://47.99.108.112:3308/tanggu?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: dzyx2022cz
rocketmq:
  #mq的nameserver地址
  name-server: 47.110.240.168:9876


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true